### PR TITLE
feat: added pr specific file checking

### LINKED ISSUE #36: Feature request: PR validator should only run against changed files
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

It's inevitable that some files will fall behind as new features are introduced to the app. 

At the moment French is lagging behind which is causing all PRs to look like they are failing. We need to update the validator that runs on GH to just run against changed files / those affected by the PR.

It is still worth keeping the check that runs against all files in the codebase for local checking, so adding another script would be awesome

### What solution would you like to see?

An additional script that runs validation against changed files only in the GH action

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by umuthopeyildirim**
# Explain your changes
Fixes #36 by updating `validate-json.py` to allow the validation of specific `auth.json` files passed as arguments. 

# Checklist

- [x] I have read the [“Pull requests” section](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md#pull-requests) in the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md).

🛟 _If you need help, consider asking for advice over in the [Kinde community](https://thekindecommunity.slack.com)._

### CODE REVIEW

**Comment by DaveOrDead** [comment]
@umuthopeyildirim this looks awesome!

Are you able to update the readme with details on how to use locally?

**Comment by umuthopeyildirim** [comment]
@DaveOrDead I've updated the `validate` script functionality to include an optional `--file` parameter. Now, when this argument is provided, the script will only check the specified file.

**Review by DaveOrDead — DISMISSED** [review]
Legend thanks @umuthopeyildirim 🚀

**Comment by DaveOrDead** [comment]
@umuthopeyildirim sorry to hassle mate, it looks like it's failing: https://github.com/kinde-oss/kinde-translations/actions/runs/6764216946/job/18382902839?pr=40

**Comment by umuthopeyildirim** [comment]
Hi @DaveOrDead, Sorry for so many commits it took a lot of testing to debug this.
So problem was users need to create a fork in order to create a PR but my script was trying to find that PR branch in `kinde-oss/kinde-translations` instead of `username/kinde-translations`. With my current fixes this should be fixed.

**Review by DaveOrDead — APPROVED** [review]

**Comment by DaveOrDead** [comment]
thanks @umuthopeyildirim - let's give it a spin on your other PR :)

**Pull request merged**
