### PR TITLE
feat: Added Turkish(TR) translation

### PR DESCRIPTION
**Pull request by umuthopeyildirim**
# Explain your changes

Added full Turkish(TR) translation for Kinde.

# ❗ Help Needed
In English `'Powered By '+${business_name}` makes sense but in Turkish it needs to be rearranged to `${business_name}+' Powered By'`. Any help on this is appreciated.
Problematic translation title is `"credit_powered_by"`

# Checklist

- [x] I have read the [“Pull requests” section](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md#pull-requests) in the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by DaveOrDead** [comment]
Hey @umuthopeyildirim, looks awesome - thanks!

Regarding the `Powered by` text, it is a tricky one.

It's for this logo
Screenshot 2023-11-06 at 11 00 04 am
where the "Powered by" is regular text and the Kinde logo is an svg. We therefore visually hide the "Kinde" text so it can still be announced for assistive technologies such as screen readers
Screenshot 2023-11-06 at 1 00 10 pm

This makes it a bit tricky in this instance to change the positioning of the business name in the text. Do you think in this use case it would be ok for the Turkish translation to be out of order or would it cause too much confusion?

**Comment by umuthopeyildirim** [comment]
@DaveOrDead I think it would be best to keep the `Powered by` section blank at the moment, as the current options would require either relocating the text or settling for an incorrect translation.

**Comment by DaveOrDead** [comment]
@umuthopeyildirim that works, if it is blank it will fall back to English, which probably works fine in this instance. Thanks for looking into it :)

**Comment by umuthopeyildirim** [comment]
Hi @DaveOrDead removed `powered_py` translation so it can fallback to default. Seems like github actions is not working?

**Comment by DaveOrDead** [comment]
@umuthopeyildirim yeah not sure what has happened there...

**Comment by umuthopeyildirim** [comment]
I can see it triggering on my PR and passing. https://github.com/umuthopeyildirim/kinde-translations/actions/runs/6781072826/job/18430746561

**Comment by umuthopeyildirim** [comment]
Got it, issue is still caused by remote PR branches. We should change
```
name: Translations - JSON Schema Validation

on:
  push:
    branches:
      - "*"
      - "*/*"
```
to 
```
name: Translations - JSON Schema Validation

on:
  pull_request:
    branches:
      - "*"
      - "*/*"
```

**Comment by umuthopeyildirim** [comment]
@DaveOrDead Actions works and passes 😄

**Review by DaveOrDead — APPROVED** [review]

**Pull request merged**
